CC = gcc
FLAGS = -Wall -Wextra -Werror
INCLUDES = -I includes/
SRCS = srcs/ft_putchar.c srcs/ft_swap.c srcs/ft_putstr.c srcs/ft_strlen.c srcs/ft_strcmp.c
LIB = libft.a
OBJS = $(SRCS:.c=.o) #remplacer lextension de srcs en .o

all: $(LIB)

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(LIB_A)


